version: '3.8'

services:
  tgforwarderclient:
    image: ghcr.io/qqalexqq/tgforwarderclient:latest
    command: run
    environment:
      BOT_API_ID: ${API_ID}
      BOT_API_HASH: ${API_HASH}
      BOT_CHANNELS: |
        techsparks
        g33ks
        blognot
        radio_t_podcast
        durov_russia
        daily_geek_news
        random_science
        asdfajsdfkl
      BOT_CHATS: |
        -1001005702961
      BOT_SESSION_KEY: ${SESSION_KEY}
    restart: always
