---
- name: Deploy and restart service
  hosts: all
  tasks:
    -
      name: Install a list of packages
      apt:
        autoclean: true
        update_cache: true
        pkg:
          - python3
          - python3-pip
          - python3-setuptools
          - rsync
    -
      name: Install docker package for python
      pip:
        name:
          - pip
          - docker-compose
          - docker~=5.0.0
    -
      name: Create deployment directory
      file:
        path: ~/bot/
        state: directory
    -
      name: Clean old services files
      file:
        state: absent
        path: ~/bot/
    -
      name: Synchronize
      synchronize:
        src: "{{ deploy_dir_src }}"
        dest: ~/bot/
        recursive: true
        mode: push
    -
      name: Docker Compose UP
      environment:
        API_ID: "{{ bot_api_id }}"
        API_HASH: "{{ bot_api_hash }}"
        SESSION_KEY: "{{ bot_session_key }}"
      docker_compose:
        project_src: ~/bot/
        recreate: smart
        pull: true
        remove_orphans: true
    -
      name: Prune docker images and cache
      community.docker.docker_prune:
        images: true
        builder_cache: true
